# This file is machine-generated - editing it directly is not advised

[[FastPrimeSieve]]
path = "/scratch/snx3000/hstoppel/julia_dev/FastPrimeSieve"
uuid = "715f0e73-5d43-4f21-b094-9019e1b56aa3"
version = "0.1.0"
